plugins {
    id 'java'
    id 'net.serenity-bdd.serenity-gradle-plugin' version '3.9.8'
}

group = 'com.automatizacion'
version = '1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'net.serenity-bdd:serenity-core:3.9.8'
    testImplementation 'net.serenity-bdd:serenity-cucumber:3.9.8'
    testImplementation 'net.serenity-bdd:serenity-screenplay-webdriver:3.9.8'
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.18.1'
    testImplementation 'io.cucumber:cucumber-java:7.15.0'
    testImplementation 'io.cucumber:cucumber-junit:7.15.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'io.github.bonigarcia:webdrivermanager:5.7.0'
}

test {
    systemProperty 'cucumber.filter.tags', System.getProperty('cucumber.filter.tags', '')
}